### ISSUE TITLE
可以解析但无法下载 and 无法检测更新

### ISSUE THREAD

**Issue by Jziumo** [leiurayer/downkyi#117]
【1.4.0版本】视频可以解析，但下载的时候会下载失败。（这个问题时不时出现，有时候是好的）
然后检测更新时会显示失败，无论是不是最新版本。
谢谢大神！(*￣3￣)╭
![P1](https://user-images.githubusercontent.com/70738205/130001697-7da13d9f-3981-4469-a01d-8d74804d1e3d.JPG)
![P2](https://user-images.githubusercontent.com/70738205/130001708-fcfb74f9-6e18-432c-a17a-87533094345e.JPG)

**Comment by DannyJRu** [comment]
我也遇到了同样的问题

**Comment by leiurayer** [comment]
偶尔下载失败的问题的确存在，正在修复；
软件更新的服务器没了，所以暂时无法更新

**Comment by DannyJRu** [comment]
不是偶尔，我昨晚试了几个都不行，前几天下的几个都行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leiurayer/downkyi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月28日(星期六) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leiurayer/downkyi] 可以解析但无法下载 and 无法检测更新 (#117)





 
偶尔下载失败的问题的确存在，正在修复；
 软件更新的服务器没了，所以暂时无法更新
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DannyJRu** [comment]
我发现一个特点，多part的视频就可以正常下载，单part的就不行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leiurayer/downkyi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月28日(星期六) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leiurayer/downkyi] 可以解析但无法下载 and 无法检测更新 (#117)





 
偶尔下载失败的问题的确存在，正在修复；
 软件更新的服务器没了，所以暂时无法更新
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Jziumo** [comment]
> 
> 
> 偶尔下载失败的问题的确存在，正在修复；
> 软件更新的服务器没了，所以暂时无法更新

最近几次下载都用得很顺~
